---
- name: remove host entry from ~/.ssh/known_hosts
  connection: local
  command: ssh-keygen -R {{ inventory_hostname }}
  ignore_errors: true

- name: clone buildroot
  git: repo=https://github.com/xenserver/buildroot dest=/usr/src/xenbuilder/buildroot

# XXX: Needs to be separated from the stanza below because ansible's yum module does not
#      repopulate the cache in between installs even with update_cache=yes
- name: install epel-release
  sudo: yes
  yum: name=epel-release state=latest

- name: install dependencies
  sudo: yes
  yum: name={{ item }} state=present 
  with_items:
    - mock
    - redhat-lsb-core
    - screen

- name: add xenbuilder to group mock
  user: name=xenbuilder groups=mock,wheel
  sudo: yes
  tags:
